controller_frequency: 10
use_obstacles: false

CollvoidLocalPlanner:
  holo_robot: false
  wheel_base: 0.25
  
  max_vel_x: 0.35
  max_vel_th: 1.5
  min_vel_x: 0.05
  min_vel_th: 0.1
  min_vel_y: 0.0
  max_vel_y: 0.0
  min_vel_th_inplace: 0.5
  acc_lim_x: 5.0
  acc_lim_y: 5.0
  acc_lim_th: 5.2

  max_vel_with_obstacles: 0.5

  footprint_radius: 0.22


  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.10
  latch_xy_goal_tolerance: true
  ignore_goal_yaw: false
  global_frame: /map

  time_horizon_obst: 10.0
  time_to_holo: 0.4
  min_error_holo: 0.02
  max_error_holo: 0.10
  delete_observations: true
  threshold_last_seen: 0.5
  trunc_time: 10.0
  left_pref: -0.05

  eps: 0.1
  
  publish_positions_frequency: 10
  publish_me_frequency: 10

  type_vo: 0 #HRVO = 0, RVO = 1, VO = 2

  orca: false #orca or VO
  convex: true #footprint or radius
  clearpath: true #clearpath or sampling 
  num_samples: 400 #num samples
  use_truncation: true #truncate vos
  new_sampling: true