/noise_std: 0.0
use_obstacles: true

controller_frequency: 10

CollvoidLocalPlanner:
  yaw_goal_tolerance: 0.10
  xy_goal_tolerance: 0.10
  latch_xy_goal_tolerance: true
  ignore_goal_yaw: false
  global_frame: /map

  time_horizon_obst: 10.0
  time_to_holo: 0.4
  min_error_holo: 0.02
  max_error_holo: 0.10
  delete_observations: true
  threshold_last_seen: 0.5 #not implemented yet
  publish_positions_frequency: 10
  publish_me_frequency: 10

  trunc_time: 10.0
  left_pref: -0.05
  eps: 0.1
  type_vo: 0 #HRVO = 0, RVO = 1, VO = 2
  orca: true #orca or VO
  convex: true #footprint or radius
  clearpath: true #clearpath or sampling 
  num_samples: 400 #num samples
  use_truncation: true #truncate vos

